export const reducerCases = {
  SET_USER_INFO: "SET_USER_INFO",
  SET_NEW_USER: "SET_NEW_USER",
  SET_ALL_CONTACTS_PAGE: "SET_ALL_CONTACTS_PAGE",
  SET_CURRENT_CHAT_USER: "SET_CURRENT_CHAT_USER",
  SET_MESSAGES: "SET_MESSAGES",
  SET_SOCKET: "SET_SOCKET",
  ADD_MESSAG: "ADD_MESSAG",
  SET_MESSAGE_SEARCH: "SET_MESSAGE_SEARCH",
  SET_USER_CONTACTS: "SET_USER_CONTACTS",
  SET_ONLINE_USER: "SET_ONLINE_USER",
  SET_CONTACT_SEARCH: "SET_CONTACT_SEARCH",
  SET_EXIT_CHAT: "SET_EXIT_CHAT",
};
